server:
  port: 5160

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: product-service
  config:
    import: 'optional:configserver: '
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  datasource:
    url: jdbc:postgresql://localhost:5432/apang_db
    username: apang
    password: apangpass
    driver-class-name: org.postgresql.Driver

  # 임시 jpa 설정 ( 이후 config-server로 부터 받을 예정 )
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:localhost}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:3101/eureka/}

openapi:
  service:
    url: ${OPENAPI_URL:http://localhost:5160}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    # 접속 후 API 그룹이 잘 보이도록 설정
    operations-sorter: method
  api-docs:
    path: /api-docs
